aidaninja/SSTK_front

.storybook/config.js
package.json
src/App.js
yarn.lock

・styled-componentsにreset cssを適用
・storybookにもreset cssを適用

reset cssを適用

---

src/components/atoms/button/ButtonBase.jsx
src/components/atoms/button/index.stories.js
src/components/atoms/buttons/ButtonBase.jsx
src/components/atoms/buttons/index.stories.js

ボタンコンポーネントを作成
・コンポーネント
・storybook

ボタンコンポーネントを作成

---

src/components/atoms/buttons/ButtonBase.jsx
src/components/atoms/buttons/index.stories.js

atoms ボタンコンポーネントを作成

---

src/components/atoms/Box/BoxBase.jsx
src/components/atoms/Box/index.stories.js
src/components/atoms/buttons/index.stories.js
src/components/atoms/inputs/index.stories.js

atoms ボックスコンポーネントを追加

---

src/components/atoms/Box/index.jsx
src/components/atoms/inputs/index.jsx
src/components/molecules/FormBox/index.jsx
src/components/molecules/FormBox/index.stories.js

ログインやサインアップ用のフォームコンポーネントを作成。それに伴いatomのinputコンポーネントの見た目のバランスを微調整。

molecules フォームコンポーネントを作成

---

src/components/atoms/Imgs/index.jsx
src/components/atoms/Imgs/index.stories.js

Imageコンポーネントに以下のバリエーションを追加
・RoundImage - radiusが50%のImage
・RoundBorderImage - radiusが50%でborderつきのImage

atoms Imageにコンポーネントを追加

---

src/components/atoms/Box/index.jsx
src/components/organisms/PostItem/index.jsx
src/components/organisms/PostItem/index.stories.js

投稿アイテム用のコンポーネントを作成、それに伴いBoxコンポーネントの余白を使用する際に設定するように変更。

organisms PostItemを作成およびatoms Boxコンポーネントの修正

---

src/components/organisms/PageHeader/index.jsx
src/components/organisms/PageHeader/index.stories.js

Organisms PageHeader

---

src/components/organisms/PostItem/index.jsx
src/components/organisms/PostItemLIst/index.jsx
src/components/organisms/PostItemLIst/index.stories.js

投稿アイテムを一覧表示するためのPostItemListコンポーネントを作成。
また、PostItemコンポーネントのTag表示にkeyが未設定だったため修正。

Organisms PostItemListの作成、PostItemの修正

---

src/components/organisms/CommentItem/index.jsx
src/components/organisms/CommentItem/index.stories.js
src/components/organisms/CommentItemList/index.jsx
src/components/organisms/CommentItemList/index.stories.js
src/components/organisms/PostItem/index.jsx

以下の2つのコンポーネントを追加
CommentItem:  コメントアイテムを表示するためのコンポーネント
CommentItemList: コメントアイテムを一覧表示するためのコンポーネント

CommentItem, CommentItemListコンポーネントを作成

---

src/components/atoms/TextInput/index.jsx
src/components/atoms/TextInput/index.stories.js

TextInputコンポーネントを作成

---

src/components/atoms/TextInput/index.jsx
src/components/molecules/TextInputBox/index.jsx
src/components/molecules/TextInputBox/index.stories.js

Text入力用のコンポーネントを作成。
inputとtextareaの切り替えが可能。

TextInputBoxを追加

---

src/components/molecules/TextInputBox/index.jsx
src/components/organisms/CommentInput/index.jsx
src/components/organisms/CommentInput/index.stories.js

CommentInputコンポーネントを作成

---

src/components/organisms/CommentItemList/index.jsx
src/components/organisms/CommentSection/index.jsx
src/components/organisms/CommentSection/index.stories.js

CommentListItemとCommentInputをあわせたコンポーネントの作成

CommentSectionコンポーネントの作成

---

src/components/molecules/TextContent/index.jsx
src/components/molecules/TextContent/index.stories.js

投稿の概要や投稿のプレビューで使用するためのコンポーネントを作成。

TextContentコンポーネントを作成

---

src/components/molecules/TextContentBox/index.jsx
src/components/molecules/TextContentBox/index.stories.js

投稿の概要などのテキストのブロックを表現するためのコンポーネントを作成。

TextContentBoxコンポーネントを作成

---

src/components/organisms/PostOverview/index.jsx
src/components/organisms/PostOverview/index.stories.js

PostOverviewコンポーネントを作成

---

src/components/organisms/SignupForm/index.jsx
src/components/organisms/SignupForm/index.stories.js

SignupFormコンポーネントを作成

---

src/components/organisms/LoginForm/index.jsx
src/components/organisms/LoginForm/index.stories.js
src/components/organisms/SignupForm/index.jsx

ログイン用のフォーム系コンポーネントを作成。
またサインアップ用のコンポーネントのボタンの文言を変更。

LoginFormコンポーネントを作成

---

.storybook/config.js
src/components/atoms/Link/index.jsx
src/components/atoms/Link/index.stories.js

Lnkコンポーネントの作成

---

src/App.jsx
src/components/molecules/FormBox/index.jsx
src/components/organisms/LoginForm/index.jsx
src/components/organisms/SignupForm/index.jsx
src/components/pages/Login/index.jsx
src/components/pages/Signup/index.jsx
src/components/templates/TopLayout.jsx

Signup、Loginページの作成

---

.gitignore
package.json
src/App.jsx
src/components/organisms/LoginForm/index.jsx
src/components/pages/Home/index.jsx
src/components/pages/Login/index.jsx
src/firebase/firebase.config.js
src/utils/firebase/firebase.utils.js

firebaseを使ったGoogleアカウントでのログインとログアウトを実装。

firebaseを使ったGoogleアカウントでのログインとログアウトを実装

---

src/App.jsx
src/components/organisms/GlobalNavigation/index.jsx
src/components/pages/Home/index.jsx
src/components/pages/Login/index.jsx
src/components/pages/Signup/index.jsx
src/utils/firebase/firebase.utils.js

・firebaseを使ったユーザ登録、ログインを実装。
・firestoreにユーザ情報を登録する処理を追加

firebaseによるユーザ登録、ログインを実装

---

src/App.jsx
src/Routes.jsx
src/contexts/AuthUser.js
src/contexts/index.js

App.jsx->Routes.js->各Componentの階層に変更して、
App.jsxにProviderを書くようにしています。
しかし、無駄にファイルを増やさない方法として、最も高い階層のindex.jsにProviderを書くこともできるので如何様にでも！

AuthUserContext作成

---

src/Routes.jsx
src/components/atoms/Imgs/index.jsx
src/components/atoms/Imgs/index.stories.js
src/components/molecules/FormBox/index.jsx
src/components/molecules/TextContent/index.jsx
src/components/organisms/CommentItem/index.jsx
src/components/organisms/CommentItem/index.stories.js
src/components/organisms/CommentItemList/index.stories.js
src/components/organisms/CommentSection/index.stories.js
src/components/organisms/EditProfileForm/index.jsx
src/components/organisms/EditProfileForm/index.stories.js
src/components/organisms/GlobalNavigation/index.jsx
src/components/organisms/PostItem/index.jsx
src/components/organisms/PostItem/index.stories.js
src/components/organisms/ProfileBox/index.jsx
src/components/organisms/ProfileBox/index.stories.js
src/components/pages/CreatePost/index.jsx
src/components/pages/Home/index.jsx
src/components/pages/Post/index.jsx
src/components/pages/Profile/index.jsx
src/components/templates/PageLayout/index.jsx
src/components/templates/TopLayout.jsx
src/components/templates/TopLayout/index.jsx
src/utils/firebase/firebase.utils.js

プロフィール画面の作成

---

src/components/organisms/MessageBox/index.jsx
src/components/organisms/MessageBox/index.stories.js
src/components/pages/CreatePost/index.jsx
src/components/pages/Post/index.jsx
src/components/pages/Profile/index.jsx

・投稿時のエラー文言の追加
・プロファイル画面にてユーザが投稿を持っていない場合の表示を追加

エラー文言・プロファイル投稿なし表示の追加

---

src/components/pages/Home/index.jsx
src/components/pages/Profile/index.jsx

- 新規投稿ページ（/post）
- 投稿のコメント（/post/[uniqueId]）
- トップページ（/）
- プロファイルページ（/profile/[userId]）

エラー機能、追従する新規投稿ボタン作成

---

src/components/molecules/FormBox/index.jsx
src/components/organisms/LoginForm/index.jsx
src/components/organisms/SignupForm/index.jsx
src/components/pages/Signup/index.jsx

- ログイン画面にサインアップへの導線を作成
- googleでサインアップ作成
- サインアップ後、下記のように画面遷移するよう修正
　・普通のサインアップ -> /profile/[userId]
　・googleサインアップ -> /
merge出来たらこのブランチ消しちゃってもいいです！あいだくん判断でお願いします。

サインアップ周り作成

---

src/Routes.jsx
src/components/molecules/TextContent/index.jsx
src/components/organisms/CommentInput/index.jsx
src/components/organisms/EditProfileForm/index.jsx
src/components/organisms/ProfileBox/index.jsx
src/components/organisms/SignupForm/index.jsx
src/components/organisms/TermsItem/index.jsx
src/components/pages/CreatePost/index.jsx
src/components/pages/EditPost/index.jsx
src/components/pages/Post/index.jsx
src/components/pages/Profile/index.jsx
src/components/pages/Signup/index.jsx

ワーニング、console.logを削除および、デザインを一部変更
